// Generated by CoffeeScript 1.7.1
var DObject;

DObject = (function() {
  function DObject(template_id, inherit_object) {
    var dom_target;
    this.template_id = template_id;
    this.inherit_object = inherit_object;
    dom_target = document.getElementById(template_id);
  }

  return DObject;

})();
